services:
  mysql-db:
    image: mysql:8.3
    container_name: mysql-books-db
    restart: always

    environment:
      - MYSQL_ROOT_PASSWORD=ryugamine.23
      - MYSQL_DATABASE=books
      - MYSQL_USER=bookstore_user
      - MYSQL_PASSWORD=ryugamine.23

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - books-network

volumes:
  mysql-data:

networks:
  books-network:
    driver: bridge
